config/routes.rb
Rails.application.routes.draw do
  get '/quotes/new'
  resources :new_tiles
  resources :quotes
  
  

end

app/models/l.rb
class L < ActiveRecord::Base
end

app/models/new_tile.rb
class NewTile < ActiveRecord::Base

end

app/models/quote.rb
class Quote < ActiveRecord::Base
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/new_tiles_controller.rb
class NewTilesController < ApplicationController
  before_action :set_new_tile, only: [:show, :edit, :update, :destroy]

  # GET /new_tiles
  # GET /new_tiles.json
  def index
    @new_tiles = NewTile.all
  end

  # GET /new_tiles/1
  # GET /new_tiles/1.json
  def show
  end

  # GET /new_tiles/new
  def new
    @new_tile = NewTile.new

  end

  # GET /new_tiles/1/edit
  def edit
  end

  # POST /new_tiles
  # POST /new_tiles.json
  def create
    @new_tile = NewTile.new(new_tile_params)

    respond_to do |format|
      if @new_tile.save
        format.html { redirect_to @new_tile, notice: 'New tile was successfully created.' }
        format.json { render :show, status: :created, location: @new_tile }
      else
        format.html { render :new }
        format.json { render json: @new_tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /new_tiles/1
  # PATCH/PUT /new_tiles/1.json
  def update
    respond_to do |format|
      if @new_tile.update(new_tile_params)
        format.html { redirect_to @new_tile, notice: 'New tile was successfully updated.' }
        format.json { render :show, status: :ok, location: @new_tile }
      else
        format.html { render :edit }
        format.json { render json: @new_tile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_tiles/1
  # DELETE /new_tiles/1.json
  def destroy
    @new_tile.destroy
    respond_to do |format|
      format.html { redirect_to new_tiles_url, notice: 'New tile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_tile
      @new_tile = NewTile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_tile_params
      params.require(:new_tile).permit(:original_image)
    end
end

app/controllers/public_data_controller.rb
class PublicDataController < ApplicationController
  def index
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    def Quote
      random_offset = rand(Quote.count - 1)
      @random_quote = Quote.offset(random_offset).first
    end

    def search
      #respond with json
      @quotes = Quote.sample

      render :json => @quote
    end

    def random
      #get random quote
      #respond with json
      
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_tiles_helper.rb
module NewTilesHelper
end

app/helpers/public_data_helper.rb
module PublicDataHelper
end

app/helpers/public_helper.rb
module PublicHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/tile_helper.rb
module TileHelper
	#form_tag({:controller => :hooks, :action => :update, :file => @myfilename}, {:method => :put}) do
	#[...]

	#end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TileCreator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/new_tiles/edit.html.erb
<div id="header" height="400px" style="background-color: #424242">
<h1 style="font-family: Futura; color: white">Create Original Content</h1>
</div>

<%= render 'form' %>



<%= link_to 'Show', @new_tile %> |
<%= link_to 'Back', "/new_tiles" %>

app/views/new_tiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 text align = center>Created Tiles</h1>

<table>
  <thead>
    <tr>
      

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody text align = center>
    <% @new_tiles.each do |new_tile| %>
      <tr>
        
        
        <td><%= image_tag new_tile.output_image_url(:thumb) %></td>
        <td><%= link_to 'Show', new_tile %></td>
        <td><%= link_to 'Edit', edit_new_tile_path(new_tile) %></td>
        <td><%= link_to 'Destroy', new_tile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New tile', new_new_tile_path %>

app/views/new_tiles/new.html.erb
<%= render 'form' %>

app/views/new_tiles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_new_tile_path(@new_tile) %> |
<%= link_to 'Back', "/new_tiles" %>

app/views/public_data/index.html.erb
<h1>PublicData#index</h1>
<p>Find me in app/views/public_data/index.html.erb</p>

app/views/quotes/index.html.erb
<h1>Listing quotes</h1>
 
<table>
  <tr>
    <th>Quote</th>
  </tr>
 
  <% @quote.each do |quote| %>
    <tr>
      <td><%= quote.text %></td>
    </tr>
  <% end %>
</table>

app/views/quotes/new.html.erb
<h1>Add Quote</h1>

<%= form_for :quote, url: quotes_path do |f| %>
  <p>
    <%= f.label :quote %><br>
    <%= f.text_area :quote %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/quotes/show.html.erb
<p>
  <strong>Quote:</strong>
  <%= @quote.text %>
</p>

app/views/tile/index.html.erb
<!-- <html>
<h1> Images </h1>
<head>


<style>
div.img {
    margin: 5px;
    padding: 5px;
    border: 1px solid #000000;
    height: auto;
    width: auto;
    float: left;
    text-align: center;
}

div.img img {
    display: inline;
    margin: 5px;
    border: 1px solid #ffffff;
}

div.img a:hover img {
    border:1px solid #000000;
}

div.desc {
    text-align: center;
    font-weight: normal;
    width: 120px;
    margin: 5px;
}
</style>
</head>
<body>

<div class="img">
  <a target="_blank" href="abstractnature.gif">
    <img src="abstractnature.gif" alt="Image" width="200" height="200">
  </a>
  <div class="desc">Add a description of the image here</div>

</div>
<div class="img">
  <a target="_blank" href="/hobbies.gif">
    <img src="/hobbies.gif" alt="Image" width="200" height="200">
  </a>
  <div class="desc">Add a description of the image here</div>
</div>



<input type="text">
<input type="file">

</body>
</html>

<script type="text/javascript">
function draw() {
   
   //var cimg = document.getElementById('imgCanvas').getContext('2d');
   var ctx = document.getElementById('textCanvas').getContext('2d');
   ctx.canvas.width  = 640;
   ctx.canvas.height = 640;
   var img = new Image();
   
   img.onload = function(){
     ctx.drawImage(img,0,0);
     
     ctx.fillStyle = 'blue';
     ctx.font = '24pt Calibri';
     ctx.align = 'left'

  	 
  	 ctx.fillText("Inspiration is something", 320,300);
  	 ctx.fillText("found beneath passion", 320,320);
  	 ctx.fillText("but above desire", 320,340);
  	};
  	img.src="http://tramuntana.tk/wp-content/uploads/nature-30794.jpg";
  	
}
draw()
	
</script>
 -->